import React from "react";
import { StyledRegisterVideo } from "./styles";
import { videoService } from "../../services/videoService";

const videoSrv = videoService();

// Custom Hook
function useForm(propsDoForm) {
    const [values, setValues] = React.useState(propsDoForm.initialValues);
    return {
        values,
        handleChange: (evento) => {
            const value = evento.target.value;
            const name = evento.target.name;
            setValues({
                ...values,
                [name]: value,
            });
        },
        clearForm: () => {
            setValues({});
        }
    }
}


// Generated by GPT
function getThumbnail(videoUrl) {
    const videoId = videoUrl.split("v=")[1];
    const thumbnailUrl = `https://img.youtube.com/vi/${videoId}/hqdefault.jpg`;
    return thumbnailUrl;
}


export default function RegisterVideo() {
    const [formVisivel, setFormVisivel] = React.useState(false);
    const formCadastrado = useForm({
        initialValues: { titulo: "title...", url: "http://...." }
    });

    /**
     * TODO
     * [X] Botão para adicionar vídeo
     * [X] Modal
     *   --> [X] Controlar o state
     *   --> [X] Formulário
     *      --> [X] pegar os dados dos inputs
     *      --> [X] submit do formulário
     *      --> [X] limpar os inputs
     */
    return (
        <StyledRegisterVideo>
            <button className="add-video" onClick={() => setFormVisivel(true)}>
                +
            </button>
            {/* Ternário*/}
            {/* Operadores de curto-circuito --> true && "do something" */}
            {formVisivel
                &&
                <form onSubmit={(evento) => {
                    evento.preventDefault();

                    const novoVideo = {
                        title: formCadastrado.values.titulo,
                        url: formCadastrado.values.url,
                        thumb: getThumbnail(formCadastrado.values.url),
                        playlist: formCadastrado.values.playlist,
                    }

                    // Contrato entre o front x backend
                    videoSrv.insert(novoVideo)
                        .then((response) => {
                            console.log("response", response);
                        })
                        .catch((err) => {
                            console.log("erro", err);
                        })

                    setFormVisivel(false);
                    formCadastrado.clearForm();
                }}>
                    <div>
                        <button type="button" className="close-modal" onClick={() => setFormVisivel(false)}>
                            X
                        </button>
                        <input
                            placeholder="Título do Vídeo"
                            name="titulo"
                            values={formCadastrado.values.titulo}
                            onChange={formCadastrado.handleChange}
                        />
                        <input
                            placeholder="URL"
                            name="url"
                            values={formCadastrado.values.url}
                            onChange={formCadastrado.handleChange}
                        /*
                        código inicial:

                        onChange={(evento) => {
                            const value = evento.target.value;
                            setValues({
                                ...values,
                                url: value,
                            });
                        }}
                        */
                        />
                        <select
                            placeholder="Playlist"
                            name="playlist"
                            values={formCadastrado.values.playlist}
                            onChange={formCadastrado.handChange}
                        >
                            <option value="Músicas">Músicas</option>
                            <option value="Jogos">Jogos</option>
                            <option value="Filmes">Filmes</option>
                            <option value="Outros">Outros</option>
                        </select>
                        <button type="submit">
                            Cadastrar
                        </button>
                    </div>
                </form>
                /* Could be:
                    {formVisivel 
                        ?
                        put here the form
                        : 
                        nothing
                
                */
            }


        </StyledRegisterVideo>
    );
}